### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Wingysam** [krestaino/my-dash#1]
Hi! Thanks for making this!

Is it possible that this can be on Docker Hub?

Thanks!

**Comment by krestaino** [comment]
Hello!

I am soon adding docker support. For now, thanks to @albertoxamin, basic support has been added.

**Comment by krestaino** [comment]
I've added support for Docker. Let me know if it works well for you.

**Comment by Wingysam** [comment]
Thanks! I ran `API_PORT=10102 UI_PORT=10101 docker-compose up` and this is what it ended with:

```
my-dash    | yarn run v1.17.3
my-dash    | $ dotenv -e .env concurrently "yarn serve:api" "yarn serve:ui"
my-dash    | [0] $ yarn --cwd api/ serve
my-dash    | [1] $ yarn --cwd ui/ serve
my-dash    | [1] $ node src/server.js
my-dash    | [0] $ node build/index.js
my-dash    | [1] UI:  Accepting connections at http://localhost:undefined
my-dash    | [0] API: Accepting connections at http://localhost:undefined
```

**Comment by krestaino** [comment]
Hi, sorry for the late response. Did you follow [this part](https://github.com/krestaino/my-dash#environmental-variables) of the readme? You need to create an `.env` file at the root of the project and add all your environmental variables there. Then just run `docker-compose up`.

I'm still new to using Docker, so I could be wrong, but the command `API_PORT=10102 UI_PORT=10101 docker-compose up` doesn't seem valid. I know with Node you can set environmental variables like `PORT=9999 node server.js`, but I'm not sure if you can do the same with Docker. Perhaps a different command would work, I'm not sure.

But again, the intention is for you to create an `.env` file at the root of the project. Follow [this file](https://github.com/krestaino/my-dash/blob/master/.env.template) as an example.

**Comment by Wingysam** [comment]
Sorry, I ended up not using this because I only use uptime robot and not any of the other services that this interfaces with.
