### ISSUE TITLE
Port undefined

### ISSUE THREAD

**Issue by aaruni96** [krestaino/my-dash#11]
**Describe the bug**
`yarn serve` gives 
```
[1] UI:  Accepting connections at http://localhost:undefined
[0] API: Accepting connections at http://localhost:undefined
```

**To Reproduce**
1. Git clone
2. cp .env.template default.env
3. yarn setup
4. yarn build
5. yarn serve

**Expected behavior**
terminal should report a port not `undefined`.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 19.10

**Additional context**
Probably related to the other issue which was closed due to inactivity.

**Comment by krestaino** [comment]
Change this.

2) `cp .env.template .env`

Sorry for the late response.
